### ISSUE TITLE
Introductory example?

### ISSUE THREAD

**Issue by ghproek** [vandenheuvel/relp#48]
Thanks for the nice repository.

I'd like to solve an LP thats generated in another program (not read from a file), but I'm getting stuck on the basic mechanics (the docs are clearly organized but deeply nested).  Would it be possible to include a simple "soup to nuts" example somewhere in the docs, that starts by defining a constraint matrix/constant vector/objective, passes them to the solver, and returns a solution?

**Comment by vandenheuvel** [comment]
Hi @ghproek!

Have you tried the `examples/` directory?
